export const teams = [
    {
        id:1,
        clubName:'Barcelona',
        img:"https://cdn.freebiesupply.com/logos/thumbs/2x/fc-barcelona-logo.png",
        vote:0
    },
    {
        id:2,
        clubName:'Juventus',
        img:"https://purepng.com/public/uploads/large/purepng.com-juventus-logojuventuslogojuventus-turin-logonew-21529676316hzqzr.png",
        vote:0
    },
    {
        id:3,
        clubName:'Manchester',
        img:"https://i.pinimg.com/originals/5f/7d/b6/5f7db63e2c0fc694aef02f1c64a31aab.jpg",
        vote:0
    }
]